blank_issues_enabled: false
contact_links:
  - name: Nano.Community Discussions
    url: https://github.com/mistakia/nano-community/discussions
    about: For general questions and discussions (not node related)
